/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as R404Import } from './routes/__404'

// Create Virtual Routes

const LobbyLazyImport = createFileRoute('/lobby')()
const CreateLazyImport = createFileRoute('/create')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const LobbyLobbyIdLazyImport = createFileRoute('/lobby/$lobbyId')()
const GameGameIdLazyImport = createFileRoute('/game/$gameId')()
const CreateLobbyIdLazyImport = createFileRoute('/create/$lobbyId')()

// Create/Update Routes

const LobbyLazyRoute = LobbyLazyImport.update({
  path: '/lobby',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/lobby.lazy').then((d) => d.Route))

const CreateLazyRoute = CreateLazyImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const R404Route = R404Import.update({
  id: '/__404',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LobbyLobbyIdLazyRoute = LobbyLobbyIdLazyImport.update({
  path: '/lobby/$lobbyId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/lobby_.$lobbyId.lazy').then((d) => d.Route),
)

const GameGameIdLazyRoute = GameGameIdLazyImport.update({
  path: '/game/$gameId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/game_.$gameId.lazy').then((d) => d.Route))

const CreateLobbyIdLazyRoute = CreateLobbyIdLazyImport.update({
  path: '/create/$lobbyId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create_.$lobbyId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/__404': {
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      preLoaderRoute: typeof CreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/lobby': {
      preLoaderRoute: typeof LobbyLazyImport
      parentRoute: typeof rootRoute
    }
    '/create/$lobbyId': {
      preLoaderRoute: typeof CreateLobbyIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId': {
      preLoaderRoute: typeof GameGameIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/lobby/$lobbyId': {
      preLoaderRoute: typeof LobbyLobbyIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  R404Route,
  AboutLazyRoute,
  CreateLazyRoute,
  LobbyLazyRoute,
  CreateLobbyIdLazyRoute,
  GameGameIdLazyRoute,
  LobbyLobbyIdLazyRoute,
])

/* prettier-ignore-end */
